### ISSUE TITLE
Data corpus for Data Visual Analytics

### ISSUE THREAD

**Issue by ChaiBapchya** [PredixDev/predix-volcano-app#12]
So I tried to search for getting access to data for visualizing and analysing at as part of my class project. I wanted to know what quantum of data corpus are we looking at? I was unable to get data points?

Expectation - second by second data record of various parameteres - C02,H2S,PA,TCA,HUMA

atleast 15-20mb worth data.
Is that possible to retrieve? Whats the relevant api call?

**Comment by j12y** [comment]
Hi @ChaiBapchya,

The [Volcano Data](https://github.com/PredixDev/predix-volcano-app#volcano-data) section of the readme lists a third option that may be helpful for you to get access to the data.  You can download the full dataset as [CSV files](https://github.com/PredixDev/predix-volcano-app/tree/master/setup/data) if that is useful.

It is a static data set since the sensors were ultimately destroyed by the volcano.  The purpose of the API is simply to demonstrate a very basic how to get started using Predix Services to store and retrieve Time Series and Asset data from a real streaming Industrial IoT solution displayed in a web ui.

We don't have any additional data from Masaya at this time.
